Web/KarlovoPharm.Web/Controllers/AboutController.cs
namespace KarlovoPharm.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class AboutController : BaseController
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/KarlovoPharm.Web/Controllers/ContactsController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;
    using KarlovoPharm.Common;
    using KarlovoPharm.Services.Messaging;
    using KarlovoPharm.Web.InputModels.Contacts;
    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : BaseController
    {
        private const string EmailSendSuccessMessage = "Вашият имейл беше успешно изпратен!";

        private readonly IEmailSender emailSender;

        public ContactsController(IEmailSender emailSender)
        {
            this.emailSender = emailSender;
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> SendEmail(EmailCreateInputModel emailCreateInputModel)
        {

            if (!this.ModelState.IsValid)
            {
                return this.Redirect(nameof(this.Contact));
            }

            await this.emailSender.SendEmailAsync(
                emailCreateInputModel.Email,
                emailCreateInputModel.Name,
                GlobalConstants.AdminEmail,
                emailCreateInputModel.Subject,
                emailCreateInputModel.Message);

            this.TempData["InfoMessage"] = EmailSendSuccessMessage;

            return this.RedirectToAction(nameof(this.Contact));
        }
    }
}

Web/KarlovoPharm.Web/Controllers/StoreController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Common;
    using KarlovoPharm.Services.Data.Products;
    using KarlovoPharm.Web.Paging;
    using KarlovoPharm.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Mvc;

    public class StoreController : BaseController
    {
        private readonly IProductService productService;

        public StoreController(IProductService productService)
        {
            this.productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> All(int? pageNumber, string sortOrder, string searchString)
        {
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["CurrentPage"] = pageNumber;
            this.ViewData["SearchString"] = searchString;

            var products = this.productService.GetAll<ProductSingleViewModel>(searchString);

            products = this.productService.OrderProducts(sortOrder, products);

            return this.View(await PaginatedList<ProductSingleViewModel>
                .CreateAsync(products, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AllFiltered(string id, int? pageNumber, string sortOrder, string searchString)
        {
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["CurrentPage"] = pageNumber;
            this.ViewData["SearchString"] = searchString;

            var productsByCategory = this.productService.GetAllBySubCategory<ProductSingleViewModel>(id, searchString);

            productsByCategory = this.productService.OrderProducts(sortOrder, productsByCategory);

            return this.View(await PaginatedList<ProductSingleViewModel>
               .CreateAsync(productsByCategory, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }
    }
}

Web/KarlovoPharm.Web/Views/Shared/Partials/_FooterPartial.cshtml
@using KarlovoPharm.Web.ViewComponents
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
                <h3 class="footer-heading mb-4">За нас</h3>
                <p>
                    Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum
                </p>
                <p>
                    <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика за ползване</a>
                </p>

            </div>

        </div>

        @await Component.InvokeAsync(typeof(FooterLinksComponent))


        <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
                <h3 class="footer-heading mb-4">Връзка с нас</h3>
                <ul class="list-unstyled">
                    <li class="address">"lorem ipsum</li>
                    <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                    <li class="email">karlovopharm@abv.com</li>
                </ul>
            </div>
        </div>


    </div>
</div>

Web/KarlovoPharm.Web/Views/Shared/Partials/_NavbarPartial.cshtml
@using KarlovoPharm.Web.ViewComponents
@using KarlovoPharm.Data.Models.Common
@using Microsoft.AspNetCore.Identity
@using KarlovoPharm.Common
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<div class="container">
    <div class="d-flex align-items-center justify-content-between">
        <div class="logo">
            <div class="site-logo">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="js-logo-clone">Karlovo Pharm</a>
            </div>
        </div>
        <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
                <ul class="site-menu js-clone-nav d-none d-lg-block">
                    <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index">Към сайта</a></li>
                    <li><a asp-area="" asp-controller="Store" asp-action="All">Магазин</a></li>
                    @await Component.InvokeAsync(typeof(NavBarCategoryComponent))
                    <li><a asp-area="" asp-controller="About" asp-action="Index">За нас</a></li>
                    <li><a asp-area="" asp-controller="Contacts" asp-action="Contact">Свържете се с нас</a></li>
                </ul>
            </nav>
        </div>
        @if (this.SignInManager.IsSignedIn(this.User))
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var user = await UserManager.GetUserAsync(this.User);
                var userId = user?.Id;
                @await Component.InvokeAsync(typeof(ShoppingCartComponent), userId)
            }
            else if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                @await Component.InvokeAsync(typeof(AdminPurchasesComponent))
            }
        }
        <partial name="~/Views/Shared/Partials/_LoginPartial.cshtml" />
    </div>
</div>