Web/KarlovoPharm.Web/Controllers/HomeController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Diagnostics;

    using KarlovoPharm.Common;
    using KarlovoPharm.Web.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {

        [Route("/")]
        [HttpGet]
        public IActionResult Index()
        {

            return this.View();
        }


        [HttpGet]
        public IActionResult InternalServer()
        {
            return this.StatusCode(500);
        }


        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int? statusCode = null)
        {
            var errorViewModel = new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier, StatusCode = statusCode };

            if (statusCode == StatusCodes.NotFound)
            {
                return this.View("ErrorNotFound", errorViewModel);
            }

            return this.View("ErrorInternalServer", errorViewModel);
        }
    }
}

Web/KarlovoPharm.Web/Controllers/ShoppingCartController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Data.Models.Common;
    using KarlovoPharm.Services.Data.ShoppingCartProducts;
    using KarlovoPharm.Services.Data.ShoppingCarts;
    using KarlovoPharm.Web.InputModels.ShoppingCartProducts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;
        private readonly IShoppingCartProductsService shoppingCartProductsService;
        private readonly UserManager<ApplicationUser> userManager;

        public ShoppingCartController(
            IShoppingCartService shoppingCartService,
            IShoppingCartProductsService shoppingCartProductsService,
            UserManager<ApplicationUser> userManager)
        {
            this.shoppingCartService = shoppingCartService;
            this.shoppingCartProductsService = shoppingCartProductsService;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var shoppingCartId = await this.shoppingCartService.GetIdByUserId(user.Id);

            var shoppingCartProducts = await this.shoppingCartProductsService.GetAllProductsAsync<ShoppingCartProductInputModel>(shoppingCartId);

            return this.View(shoppingCartProducts);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> QuantityEdit(string productId, int quantity)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.shoppingCartProductsService.QuantityEdit(productId, quantity, user.Id);

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(string productId)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.shoppingCartProductsService.Delete(productId, user.Id);

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/KarlovoPharm.Web/Controllers/StoreController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Common;
    using KarlovoPharm.Services.Data.Products;
    using KarlovoPharm.Web.Paging;
    using KarlovoPharm.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Mvc;

    public class StoreController : BaseController
    {
        private readonly IProductService productService;

        public StoreController(IProductService productService)
        {
            this.productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> All(int? pageNumber, string sortOrder, string searchString)
        {
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["CurrentPage"] = pageNumber;
            this.ViewData["SearchString"] = searchString;

            var products = this.productService.GetAll<ProductSingleViewModel>(searchString);

            products = this.productService.OrderProducts(sortOrder, products);

            return this.View(await PaginatedList<ProductSingleViewModel>
                .CreateAsync(products, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AllFiltered(string id, int? pageNumber, string sortOrder, string searchString)
        {
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["CurrentPage"] = pageNumber;
            this.ViewData["SearchString"] = searchString;

            var productsByCategory = this.productService.GetAllBySubCategory<ProductSingleViewModel>(id, searchString);

            productsByCategory = this.productService.OrderProducts(sortOrder, productsByCategory);

            return this.View(await PaginatedList<ProductSingleViewModel>
               .CreateAsync(productsByCategory, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }
    }
}

Web/KarlovoPharm.Web/Views/Home/Index.cshtml
@using KarlovoPharm.Web.ViewComponents



    <div class="site-blocks-cover" style="  background-image: url(https://res.cloudinary.com/dqe7qcizi/image/upload/v1586517396/common_images/hero_1_jqh3af.jpg);
">

        @if (this.TempData["Status"] != null)
        {
            @await Component.InvokeAsync("InfoMessage", new { message = this.TempData["Status"] });
        }
        <div class="container">
            <div class="row">
                <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
                    <div class="site-block-cover-content text-center">
                        <h2 class="sub-title">Ефективни лекарства, Нови лекарства всеки ден</h2>
                        <h1>Добре дошли в Карлово Фарм </h1>
                        <p>
                            <a asp-controller="Store" asp-action="All" class="btn btn-primary px-5 py-3">Пазарувайте сега</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="site-section">
    <div class="container">
        <div class="row align-items-stretch section-overlap">
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                <div class="banner-wrap bg-primary h-100">
                    <a asp-controller="ShoppingCart" asp-action="Index" class="h-100">
                        <h5>Безплатна <br> Доставка</h5>
                        <p>
                            Безплатна доставка при поръчка над 20 лв.
                        </p>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                <div class="banner-wrap h-100">
                    <a asp-controller="Store" asp-action="All" asp-route-sortOrder="products-with-discount" class="h-100">
                        <h5>Намаление <br> до 50%</h5>
                        <p>
                            Вижте
                            <strong>Всички намалени продукти</strong>
                        </p>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                <div class="banner-wrap bg-warning h-100">
                    <a href="#" class="h-100">
                        <h5>Възможност <br> за отстъпка</h5>
                        <p>
                            Възползвайте се от промо-код
                            <strong>За да получите намаление при поръчка.</strong>
                        </p>
                    </a>
                </div>
            </div>

        </div>
    </div>
</div>


@await Component.InvokeAsync(typeof(PopularProductsComponent))


@await Component.InvokeAsync(typeof(NewestProductsComponent))


@*<div class="site-section bg-secondary bg-image" style="background-image: url('images/bg_2.jpg');">
    <div class="container">
        <div class="row align-items-stretch">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <a href="#" class="banner-1 h-100 d-flex" style="background-image: url('https://res.cloudinary.com/dqe7qcizi/image/upload/v1587304330/common_images/dr-radeva_grvdrn.jpg');">
                    <div class="banner-1-inner align-self-center">
                        <h2>Pharma Products</h2>
                        <p>
                            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                        </p>
                    </div>
                </a>
            </div>
            <div class="col-lg-6 mb-5 mb-lg-0">
                <a href="#" class="banner-1 h-100 d-flex" style="background-image: url('https://res.cloudinary.com/dqe7qcizi/image/upload/v1587304333/common_images/dr-radeva-2_zbktqs.jpg');">
                    <div class="banner-1-inner ml-auto  align-self-center">
                        <h2>Rated by Experts</h2>
                        <p>
                            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                        </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>*@