Web/KarlovoPharm.Web/Areas/Administration/Controllers/OrdersController.cs
namespace KarlovoPharm.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Common;
    using KarlovoPharm.Services.Data.Orders;
    using KarlovoPharm.Web.Paging;
    using KarlovoPharm.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : AdministrationController
    {
        private readonly IOrderService orderService;

        public OrdersController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> AllUnprocessed(int? pageNumber)
        {
            var unprocessedOrders = this.orderService.GetAllUnprocessed<OrderUnprocessedViewModel>();

            return this.View(await PaginatedList<OrderUnprocessedViewModel>
                .CreateAsync(unprocessedOrders, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AllProcessed(int? pageNumber)
        {
            var processedOrders = this.orderService.GetAllProcessed<OrderProcessedViewModel>();

            return this.View(await PaginatedList<OrderProcessedViewModel>
                .CreateAsync(processedOrders, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AllDelivered(int? pageNumber)
        {
            var deliveredOrders = this.orderService.GetAllDelivered<OrdereDeliveredViewModel>();

            return this.View(await PaginatedList<OrdereDeliveredViewModel>
                .CreateAsync(deliveredOrders, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string orderId)
        {
            var orderAdminDetailsViewModel = await this.orderService.DetailsAdmin<OrderDetailsAdminViewModel>(orderId);

            return this.View(orderAdminDetailsViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Process(string orderId)
        {
            await this.orderService.Process(orderId);

            return this.RedirectToAction(nameof(this.AllUnprocessed));
        }

        [HttpGet]
        public async Task<IActionResult> Renew(string orderId)
        {
            await this.orderService.Renew(orderId);

            return this.RedirectToAction(nameof(this.AllUnprocessed));
        }

        [HttpGet]
        public async Task<IActionResult> Finish(string orderId)
        {
            await this.orderService.Finish(orderId);

            return this.RedirectToAction(nameof(this.AllProcessed));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string orderId)
        {
            await this.orderService.Delete(orderId);

            return this.RedirectToAction(nameof(this.AllProcessed));
        }

        [HttpGet]
        public async Task<IActionResult> Cancel(string orderId)
        {
            await this.orderService.Cancel(orderId);

            return this.RedirectToAction(nameof(this.AllUnprocessed));
        }

    }
}

Web/KarlovoPharm.Web/Controllers/AddressesController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Services.Data.Addresses;
    using KarlovoPharm.Services.Data.Users;
    using KarlovoPharm.Services.Data.UsersAddresses;
    using KarlovoPharm.Web.InputModels.Addresses.Create;
    using KarlovoPharm.Web.InputModels.Addresses.Edit;
    using Microsoft.AspNetCore.Mvc;

    public class AddressesController : BaseController
    {
        private const string UserCantHaveMoreThanThreeAddressesErrorMessage = "Не можете да добавята повече от 3 адреса за акаунт !";

        private const string UnexpectedErrorEditingAddressErrorMessage = "Възникна грешка при опит за редакция на адрес.";

        private const string UnexpectedErrorDeletingAddressErrorMessage = "Възникна грешка при опит за изтриване на адрес.";


        private readonly IAddressService addressService;
        private readonly IUsersAddressesService usersAddressesService;
        private readonly IUserService userService;

        public AddressesController(IAddressService addressService, IUsersAddressesService usersAddressesService, IUserService userService)
        {
            this.addressService = addressService;
            this.usersAddressesService = usersAddressesService;
            this.userService = userService;
        }

        [HttpGet]
        public IActionResult Create(string userId)
        {
            var addressCreateInputModel = new AddressCreateInputModel();
            addressCreateInputModel.UserId = userId;

            return this.View(addressCreateInputModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(AddressCreateInputModel addressCreateInputModel)
        {
            if (await this.userService.UserHasThreeAddresses(addressCreateInputModel.UserId))
            {
                this.TempData["Error"] = UserCantHaveMoreThanThreeAddressesErrorMessage;
                return this.RedirectToAction("Create", addressCreateInputModel);
            }

            var address = await this.addressService.CreateAsync(addressCreateInputModel);
            await this.usersAddressesService.CreateAsync(addressCreateInputModel.UserId, address.Id);

            return this.Redirect($"/Users/Profile?userId={addressCreateInputModel.UserId}");
        }

        [HttpGet]
        public IActionResult Edit(string addressId, string userId)
        {
            var addressEditInputModel = this.addressService.GetById<AddressEditInputModel>(addressId);
            addressEditInputModel.UserId = userId;

            return this.View(addressEditInputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AddressEditInputModel addressEditInputModel)
        {
            if (!this.ModelState.IsValid ||
                await this.addressService.Edit(addressEditInputModel) == false)
            {
                this.TempData["Error"] = UnexpectedErrorEditingAddressErrorMessage;
                return this.RedirectToAction("Edit", new { addressId = addressEditInputModel.Id, userId = addressEditInputModel.UserId });
            }

            return this.Redirect($"/Users/profile?userId={addressEditInputModel.UserId}");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string addressId, string userId)
        {
            if (!await this.usersAddressesService.DeleteAsync(addressId, userId) ||
                !await this.addressService.DeleteAsync(addressId))
            {
                this.TempData["Error"] = UnexpectedErrorDeletingAddressErrorMessage;
                return this.RedirectToAction("Edit", new { addressId, userId });
            }

            return this.Redirect($"/Users/profile?userId={userId}");
        }

    }
}

Web/KarlovoPharm.Web/Controllers/OrdersController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using KarlovoPharm.Data.Models.Common;
    using KarlovoPharm.Services.Data.Orders;
    using KarlovoPharm.Services.Data.PromoCodes;
    using KarlovoPharm.Services.Data.ShoppingCartProducts;
    using KarlovoPharm.Services.Data.ShoppingCarts;
    using KarlovoPharm.Services.Mapping;
    using KarlovoPharm.Web.InputModels.Orders.Create;
    using KarlovoPharm.Web.InputModels.Orders.Display;
    using KarlovoPharm.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : BaseController
    {
        private const string DeliveryAddressCantBeNull = "Моля изберете адрес на доставката или офис на Еконт, като въведете адреса на офиса.";

        private const string ShoppingCartIsEmptyError = "Количката ви е празна ! Моля добавете продукти в нея, за да продължите.";

        private const string PromoCodeDoesNotExistErrorMessage = "Не съществува промокод с такова име!";

        private const string SomeProductsHaveBeenRemoved = "Вашата поръчка съдържаше продукти, които в момента не са налични, те бяха премахнати. Моля да ни извините.";

        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderService orderService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly IPromoCodeService promoCodeService;
        private readonly IShoppingCartProductsService shoppingCartProductsService;

        public OrdersController(
            UserManager<ApplicationUser> userManager,
            IOrderService orderService,
            IShoppingCartService shoppingCartService,
            IPromoCodeService promoCodeService,
            IShoppingCartProductsService shoppingCartProductsService)
        {
            this.userManager = userManager;
            this.orderService = orderService;
            this.shoppingCartService = shoppingCartService;
            this.promoCodeService = promoCodeService;
            this.shoppingCartProductsService = shoppingCartProductsService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var orderCreateInputModel = await this.orderService.CreateDisplayModel<OrderDisplayInputModel>(user.Id);

            if (orderCreateInputModel.ShoppingCart.ShoppingCartProducts.Count() == 0)
            {
                this.TempData["Error"] = ShoppingCartIsEmptyError;

                return this.Redirect("/ShoppingCart");
            }

            return this.View(orderCreateInputModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(OrderDisplayInputModel orderDisplayInputModel)
        {
            if ((orderDisplayInputModel.DeliveryAddressId == "on" && orderDisplayInputModel.OfficeAddress == null)
                || (orderDisplayInputModel.DeliveryAddressId == null && orderDisplayInputModel.OfficeAddress == null))
            {
                this.TempData["Error"] = DeliveryAddressCantBeNull;
                return this.RedirectToAction(nameof(this.Create));
            }

            if (!await this.promoCodeService.ExistsAsync(orderDisplayInputModel.PromoCodeName) &&
                orderDisplayInputModel.PromoCodeName != null)
            {
                this.TempData["Error"] = PromoCodeDoesNotExistErrorMessage;
                return this.RedirectToAction(nameof(this.Create));
            }

            this.ProccessCreateForm(orderDisplayInputModel);

            var user = await this.userManager.GetUserAsync(this.User);

            if (orderDisplayInputModel.PromoCodeName != null)
            {
                orderDisplayInputModel.PromoCodeId = await this.promoCodeService.GetIdByNameAsync(orderDisplayInputModel.PromoCodeName);
            }

            var orderCreateInputModel = orderDisplayInputModel.To<OrderCreateInputModel>();

            var shoppingCartId = await this.shoppingCartService.GetIdByUserId(user.Id);

            if (await this.shoppingCartProductsService.RemoveDisabledProducts(shoppingCartId))
            {
                this.TempData["Error"] = SomeProductsHaveBeenRemoved;
                return this.Redirect("/ShoppingCart");
            }

            await this.orderService.CreateUproccessedOrder(orderCreateInputModel, shoppingCartId);

            return this.RedirectToAction(nameof(this.SuccesfullPayment));
        }

        [HttpGet]
        [Authorize]
        public IActionResult SuccesfullPayment()
        {
            return this.View();
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> UserOrders()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var userOrdersViewModel = await this.orderService.UserOrders<UserOrderViewModel>(user.Id);

            return this.View(userOrdersViewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(string orderId)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var orderDetailsViewModel = await this.orderService.Details<OrderDetailsViewModel>(user.Id, orderId);

            return this.View(orderDetailsViewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Cancel(string orderId)
        {
            await this.orderService.Cancel(orderId);

            return this.RedirectToAction(nameof(this.UserOrders));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(string orderId)
        {
            await this.orderService.Delete(orderId);

            return this.RedirectToAction(nameof(this.UserOrders));
        }

        private void ProccessCreateForm(OrderDisplayInputModel orderDisplayInputModel)
        {
            if (orderDisplayInputModel.Recipient == null)
            {
                orderDisplayInputModel.Recipient = orderDisplayInputModel.FirstName;
            }

            if (orderDisplayInputModel.RecipientLastName == null)
            {
                orderDisplayInputModel.RecipientLastName = orderDisplayInputModel.LastName;
            }

            if (orderDisplayInputModel.RecipientPhoneNumber == null)
            {
                orderDisplayInputModel.RecipientPhoneNumber = orderDisplayInputModel.PhoneNumber;
            }

            if (orderDisplayInputModel.DeliveryAddressId == "on")
            {
                orderDisplayInputModel.DeliveryAddressId = null;
            }
        }
    }
}

Web/KarlovoPharm.Web/Controllers/StoreController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Common;
    using KarlovoPharm.Services.Data.Products;
    using KarlovoPharm.Web.Paging;
    using KarlovoPharm.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Mvc;

    public class StoreController : BaseController
    {
        private readonly IProductService productService;

        public StoreController(IProductService productService)
        {
            this.productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> All(int? pageNumber, string sortOrder, string searchString)
        {
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["CurrentPage"] = pageNumber;
            this.ViewData["SearchString"] = searchString;

            var products = this.productService.GetAll<ProductSingleViewModel>(searchString);

            products = this.productService.OrderProducts(sortOrder, products);

            return this.View(await PaginatedList<ProductSingleViewModel>
                .CreateAsync(products, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AllFiltered(string id, int? pageNumber, string sortOrder, string searchString)
        {
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["CurrentPage"] = pageNumber;
            this.ViewData["SearchString"] = searchString;

            var productsByCategory = this.productService.GetAllBySubCategory<ProductSingleViewModel>(id, searchString);

            productsByCategory = this.productService.OrderProducts(sortOrder, productsByCategory);

            return this.View(await PaginatedList<ProductSingleViewModel>
               .CreateAsync(productsByCategory, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }
    }
}

Web/KarlovoPharm.Web/ViewComponents/ErrorAlertViewComponent.cs
namespace KarlovoPharm.Web.Components
{
    using KarlovoPharm.Web.Components.Models;
    using Microsoft.AspNetCore.Mvc;

    [ViewComponent(Name = "ErrorAlert" )]
    public class ErrorAlertViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string message)
        {
            var viewModel = new ErrorAlertViewModel()
            {
                ErrorMessage = message,
            };

            return this.View(viewModel);
        }
    }
}

Web/KarlovoPharm.Web/Views/Orders/Create.cshtml
@model KarlovoPharm.Web.InputModels.Orders.Display.OrderDisplayInputModel


@{ var totalPrice = Model.ShoppingCart.ShoppingCartProducts.Sum(x => x.TotalPrice);}
@{ var deliveryPrice = totalPrice >= 20m ? 0m : 3.50m;}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="index.html">Към саита</a> <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Чекиране</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    @if (this.TempData["Error"] != null)
    {
        @await Component.InvokeAsync("ErrorAlert", new { message = this.TempData["Error"] });
    }
    <form asp-controller="Orders" asp-action="Create" method="post">
        <input type="hidden" asp-for="@Model.UserId" />
        <div class="container">
            <div class="row mb-5">
            </div>
            <div class="row">
                <div class="col-md-6 mb-5 mb-md-0">
                    <h2 class="h3 mb-3 text-black">Детайли за вашата поръчка</h2>
                    <div class="p-3 p-lg-5 border">
                        <div class="form-group">
                            <label for="c_country" class="text-black">Адрес на доставката <span class="text-danger">*</span></label>

                            @if (Model.UserAddresses.Count() < 3)
                            {
                                <a asp-controller="Addresses" asp-action="Create" asp-route-userId="@Model.UserId">
                                    Добавете адрес.
                                </a>
                            }

                            <div class="form-group border-primary mb-0">
                                <ul class="list-group">
                                    @foreach (var address in Model.UserAddresses)
                                    {
                                        <li class="list-group-item">
                                            <label>
                                                <input asp-for="DeliveryAddressId" type="radio" value="@address.AddressId" onclick="toggleInput()" />
                                                @address.AddressStreet @address.AddressCity, @address.AddressPostCode,  @address.AddressDescription
                                            </label>
                                        </li>
                                    }
                                    <li class="list-group-item">
                                        <label>
                                            <input name="DeliveryAddressId" type="radio" id="officeAddress" onclick="toggleInput()">
                                            До офис на Eконт.
                                        </label>
                                        <div id="OfficeAddressInputField" style="visibility:hidden">
                                            <label for="OfficeAddress">
                                                <textarea asp-for="OfficeAddress" placeholder="Моля опишете подробно адреса на офиса (град,улица/бул. и т.н.)"></textarea>
                                            </label>
                                        </div>
                                    </li>
                                </ul>
                            </div>


                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                @if (Model.FirstName != null)
                                {
                                    <input type="hidden" asp-for="@Model.FirstName" />
                                    <label for="FirstName" class="text-black">Име на получателя: </label>
                                    <span>@Model.FirstName</span>
                                }
                                else
                                {
                                    <label for="RecipientName" class="text-black">Име на получателя <span class="text-danger">*</span></label>
                                    <input asp-for="Recipient" type="text" class="form-control" placeholder="Въведете име на получателя">
                                    <span asp-validation-for="Recipient" class="text-danger"></span>
                                }
                            </div>

                            <div class="col-md-12">
                                @if (Model.LastName != null)
                                {
                                    <input type="hidden" asp-for="@Model.LastName" />
                                    <label for="FirstName" class="text-black">Фамилия на получателя: </label>
                                    <span>@Model.LastName</span>
                                }
                                else
                                {
                                    <label for="RecipientLastName" class="text-black">Фамилия на получателя: <span class="text-danger">*</span></label>
                                    <input asp-for="RecipientLastName" type="text" class="form-control" placeholder="Въведете фамилия на получателя:">
                                    <span asp-validation-for="RecipientLastName" class="text-danger"></span>
                                }
                            </div>

                            <div class="col-md-6">
                                @if (Model.PhoneNumber != null)
                                {
                                    <input type="hidden" asp-for="@Model.PhoneNumber" />
                                    <label for="PhoneNumber" class="text-black">Телефон на получателя: </label>
                                    <span>@Model.PhoneNumber</span>
                                }
                                else
                                {
                                    <label for="RecipientPhoneNumber" class="text-black">Номер на получателя: <span class="text-danger">*</span></label>
                                    <input asp-for="RecipientPhoneNumber" type="text" class="form-control" placeholder="Въведете тел. номер:">
                                    <span asp-validation-for="RecipientPhoneNumber" class="text-danger"></span>
                                }
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-6">

                    <div class="row mb-5">
                        <div class="col-md-12">
                            <h2 class="h3 mb-3 text-black">Вашата поръчка</h2>
                            <div class="p-3 p-lg-5 border">

                                <table class="table site-block-order-table mb-5">

                                    <thead>
                                        <tr>
                                            <td class="text-black font-weight-bold"><strong>Продукт:</strong></td>
                                            <td class="text-black font-weight-bold"><strong>Общо:</strong></td>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        @foreach (var product in Model.ShoppingCart.ShoppingCartProducts)
                                        {
                                            <tr>
                                                <td>@product.ProductName <strong class="mx-2">x</strong>@product.Quantity</td>
                                                <td>@(product.ProductPrice * product.Quantity) лв.</td>
                                            </tr>
                                        }

                                        <tr>
                                            <td class="text-black font-weight-bold"><strong>Доставка:</strong></td>
                                            <td class="text-black">@deliveryPrice лв.</td>
                                        </tr>
                                        <tr>
                                            <td class="text-black font-weight-bold"><strong>Обща сума (цена с ДДС):</strong></td>
                                            <td class="text-black font-weight-bold"><strong>@(totalPrice + deliveryPrice) лв.</strong></td>
                                        </tr>

                                    </tbody>
                                </table>

                                <label for="PromoCode" class="text-black">Промо-код: </label>
                                <input asp-for="PromoCodeName" type="text" class="form-control" placeholder="Въведете промо-код за отстъпка">

                                <div class="form-group">
                                    <label class="text-black">Начин на плащане <span class="text-danger">*</span></label>

                                    <div class="radio">
                                        <label asp-for="PaymentType">
                                            <input asp-for="PaymentType" type="radio" value="CashOnDelivery" checked>Наложен платеж
                                        </label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-lg btn-block" type="submit">
                                        Направи поръчка
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

<script>
    function toggleInput() {
        if (document.getElementById('officeAddress').checked) {
            document.getElementById('OfficeAddressInputField').style.visibility = 'visible';
        }
        else {
            document.getElementById('OfficeAddressInputField').style.visibility = 'hidden';
        }
    }
</script>

Web/KarlovoPharm.Web/Views/Orders/SuccesfullPayment.cshtml
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a asp-controller="Home" asp-action="Index">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Благодарим ви !</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <span class="icon-check_circle display-3 text-success"></span>
                <h2 class="display-3 text-black">Благодарим ви !</h2>
                <p class="lead mb-5">Вашата поръчка беше изпратена за обработка.</p>
                <a asp-controller="Orders" asp-action="UserOrders">Към моите поръчки.</a> <span class="mx-2 mb-0"></span> 
                <br>
                <p><a asp-controller="Store" asp-action="All" class="btn btn-md height-auto px-4 py-3 btn-primary">Обратно към магазин.</a></p>
            </div>
        </div>
    </div>
</div>

Web/KarlovoPharm.Web/Views/Orders/UserOrders.cshtml
@using KarlovoPharm.Web.ViewModels.Orders
@model IEnumerable<UserOrderViewModel>
@using KarlovoPharm.Web.Helpers
@using KarlovoPharm.Data.Models.Enums

@{
    ViewData["Title"] = "Мойте поръчки";
}


<div class="container mobile-fondsize-11">
    <div class="mobile-fondsize-20 h3 text-center text-black">@ViewData["Title"]</div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Номер</th>
                <th>Статус</th>
                <th>Цена</th>
                <th>Начин на плащане</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.Id.Substring(0, 5)</td>
                    <td>@order.OrderStatus.DisplayName()</td>
                    <td>@order.TotalPrice</td>
                    <td>@order.PaymentType.DisplayName()</td>
                    <td><a asp-controller="Orders" asp-action="Details" asp-route-orderId="@order.Id" class="btn btn-primary btn-sm mobile-fondsize-11">Детайли</a></td>
                    @if (order.OrderStatus != OrderStatus.Proccessed &&
                     order.OrderStatus != OrderStatus.Delivered &&
                     order.OrderStatus != OrderStatus.Canceled)
                    {
                        <td><a asp-controller="Orders" asp-action="Cancel" asp-route-orderId="@order.Id" class="btn btn-warning btn-sm mobile-fondsize-11">Откажи</a></td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>