Web/KarlovoPharm.Web/Controllers/ProductsController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Data.Models.Common;
    using KarlovoPharm.Services.Data.FavouriteProducts;
    using KarlovoPharm.Services.Data.Products;
    using KarlovoPharm.Services.Data.ShoppingCartProducts;
    using KarlovoPharm.Services.Data.ShoppingCarts;
    using KarlovoPharm.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private const string ProductAddedToFavourites = "Продуктът е добавен в любими";
        private const string ProductExistsInFavourites = "Продуктът вече съществува в любими";

        private const string ProductAddedInCart = "Продуктът е добавен в количка";
        private const string ProductExistsInCart = "Продуктът вече съществува в количка";

        private readonly IProductService productService;
        private readonly IFavouriteProductsService favouriteProductsService;
        private readonly IShoppingCartProductsService shoppingCartProductsService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly UserManager<ApplicationUser> userManager;

        public ProductsController( 
            IProductService productService,
            IFavouriteProductsService favouriteProductsService,
            IShoppingCartProductsService shoppingCartProductsService,
            IShoppingCartService shoppingCartService,
            UserManager<ApplicationUser> userManager
            )
        {
            this.productService = productService;
            this.favouriteProductsService = favouriteProductsService;
            this.shoppingCartProductsService = shoppingCartProductsService;
            this.shoppingCartService = shoppingCartService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Details(string productId)
        {
            var productViewModel = this.productService.GetProductDetailsById<ProductDetailsViewModel>(productId);

            return this.View(productViewModel);
        }

        [Authorize]
        [HttpPost]
        [Route("Products/AddToFavourites/{productId}")]
        public async Task<ActionResult<ProductAJAXViewModel>> AddToFavourites(ProductAJAXViewModel productAJAXViewModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var userId = user.Id;

            if (!await this.favouriteProductsService.AddAsync(productAJAXViewModel.ProductId, userId))
            {
                productAJAXViewModel.Message = ProductExistsInFavourites;
            }
            else
            {
                productAJAXViewModel.Message = ProductAddedToFavourites;
            }

            return productAJAXViewModel;
        }

        [Authorize]
        [HttpPost]
        [Route("Products/AddToCart/{productId}")]
        public async Task<ActionResult<ProductAJAXViewModel>> AddToCart(ProductAJAXViewModel productAJAXViewModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var userId = user.Id;
            var shoppingCartId = await this.shoppingCartService.GetIdByUserId(userId);

            if (!await this.shoppingCartProductsService.AddAsync(productAJAXViewModel.ProductId, shoppingCartId))
            {
                productAJAXViewModel.Message = ProductExistsInCart;
            }
            else
            {
                productAJAXViewModel.Message = ProductAddedInCart;
            }

            var productsCount = await this.shoppingCartService.GetProductsCountAsync(userId);
            productAJAXViewModel.Count = productsCount;

            return productAJAXViewModel;
        }

    }
}

Web/KarlovoPharm.Web/Controllers/ProductsFavouriteController.cs
namespace KarlovoPharm.Web.Controllers
{
    using System.Threading.Tasks;

    using KarlovoPharm.Common;
    using KarlovoPharm.Services.Data.FavouriteProducts;
    using KarlovoPharm.Web.Paging;
    using KarlovoPharm.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsFavouriteController : BaseController
    {
        private const string ProductDeleteFromFavouriteErrorMessage = "Възникна грешка при опит за премахване на продукта от любими";

        private readonly IFavouriteProductsService favouriteProductsService;

        public ProductsFavouriteController(IFavouriteProductsService favouriteProductsService)
        {
            this.favouriteProductsService = favouriteProductsService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> All(int? pageNumber, string userId)
        {
            this.TempData["UserId"] = userId;

            var userFavouriteProducts = this.favouriteProductsService.All<ProductFavouriteViewModel>(userId);

            return this.View(await PaginatedList<ProductFavouriteViewModel>
                .CreateAsync(userFavouriteProducts, pageNumber ?? GlobalConstants.DefaultPageIndex, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(string productId, string userId)
        {
            if (!await this.favouriteProductsService.DeleteAsync(productId, userId))
            {
                this.TempData["Error"] = ProductDeleteFromFavouriteErrorMessage;
                return this.RedirectToAction("All", new { userId });
            }

            return this.RedirectToAction("All", new { userId });
        }

    }
}

Web/KarlovoPharm.Web/Views/ProductsFavourite/All.cshtml
@using KarlovoPharm.Web.ViewModels.Products
@model KarlovoPharm.Web.Paging.PaginatedList<ProductFavouriteViewModel>

@{
    ViewData["Title"] = "Любими продукти";
}

@{var userId = this.TempData["UserId"]; }

<div class="container mobile-fondsize-11">
    <div class="mobile-fondsize-20 h3 text-center text-black">@ViewData["Title"]</div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Снимка</th>
                <th>Име</th>
                <th>Цена</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td><img src="@product.ProductPicture" width="50" height="50"></td>
                    <td>@product.ProductName</td>
                    <td>@product.ProductPrice</td>
                    <td>
                        <form id="productsApi" method="post"></form>
                        @if (product.ProductAvailable)
                        {
                            <a href="#" class="btn btn-warning" onclick="addToCart('@product.ProductId')">Добави в количка</a>
                        }
                    </td>
                    <td><a asp-controller="ProductsFavourite" asp-action="Delete" asp-route-productId="@product.ProductId" asp-route-userId="@product.UserId" class="btn btn-danger btn-sm mobile-fondsize-11">Премахни</a></td>
                    <td><a asp-controller="Products" asp-action="Details" asp-route-productId="@product.ProductId" class="btn btn-primary btn-sm mobile-fondsize-11">Детайли</a></td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }
    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <div class="site-block-27">
                <ul>
                    <li class="page-item @prevDisabled">
                        <a class="page-link" asp-controller="ProductsFavourite" asp-action="All" asp-route-userId="@userId" asp-route-pageNumber="1">&laquo;</a>
                    </li>
                    <li class="page-item @prevDisabled">
                        <a class="page-link" asp-controller="ProductsFavourite" asp-action="All" asp-route-userId="@userId" asp-route-pageNumber="@(Model.PageIndex - 1)">&lt;</a>
                    </li>
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item"><a class="page-link" asp-controller="ProductsFavourite" asp-route-userId="@userId" asp-action="All" asp-route-pageNumber="@i">@i</a></li>
                        @if (i > 10)
                        {
                            break;
                        }
                    }
                    <li class="page-item @nextDisabled">
                        <a class="page-link" asp-controller="ProductsFavourite" asp-action="All" asp-route-userId="@userId" asp-route-pageNumber="@(Model.PageIndex + 1)">&gt;</a>
                    </li>
                    <li class="page-item @nextDisabled">
                        <a class="page-link" asp-controller="ProductsFavourite" asp-action="All" asp-route-userId="@userId" asp-route-pageNumber="@Model.TotalPages">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script>
        function addToCart(productId) {
            var token = $("#productsApi input[name=__RequestVerificationToken]").val();
            var json = { productId: productId };

            $.ajax({
                url: "/api/productsapi/AddToCart",
                type: "POST",
                data: JSON.stringify(json),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                headers: { 'X-CSRF-TOKEN': token },
                success: function (data) {
                    $('#productsQuantity').html(data.count);
                    alert(data.message);
                },
                error: function (data) {
                    alert(data.message);
                }
            });
        }
    </script>
}